export const ORDER_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  FAILED: "FAILED",
  TIMEOUT: "TIMEOUT",
  REFUNDED: "REFUNDED",
  DISPUTED: "DISPUTED",
  CHARGEBACK: "CHARGEBACK",
} as const;

export const PAYMENT_STATUS = {
  AUTHORIZED: "AUTHORIZED",
  CAPTURED: "CAPTURED",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
} as const;
