export const CRITICAL_ROUTES = [
  "/",
  "/account",
  "/profile",
  "/search",
  "/faq",
  "/support",
  "/store",
  "/rankings",
  "/admin/login",
  "/admin",
  "/admin/tracking",
  "/admin/users",
  "/admin/support",
  "/admin/orders",
  "/admin/promotions",
  "/admin/series",
];
