function normalizeValue(value) {
  return String(value || "").trim().toLowerCase();
}

function toParagraphs(value) {
  return String(value || "")
    .trim()
    .split(/\n\s*\n/g)
    .map((paragraph) => paragraph.replace(/\s+/g, " ").trim())
    .filter(Boolean);
}

const NARRATIVE_OVERRIDES = {
  "series-001": {
    1: {
      openingParagraphs: toParagraphs(`
The arrow struck the chapel door hard enough to split the painted saint from throat to crown, and Bran felt the wind of it on his cheek before the screaming started. A second earlier he had been arguing with his little sister about stolen apples. A second later the bells of Dunmere were hammering above the fog and riders in black wolf cloaks were pouring through the outer gate like they had been waiting all winter for the town to blink.

Bran was sixteen, big enough to carry grain sacks and stupid enough to think that made him useful in a battle. He grabbed the wood axe from the chapel wall because it was the nearest thing with an edge. Father Aldren shouted at everyone to get below the crypt. Mothers dragged children by the wrists. The old men who had spent ten years bragging about border wars suddenly remembered their knees and limped toward shelter. Bran should have followed them. Instead he pushed Elara behind the altar rail and ran toward the square because he had seen his father on the wall at dawn and could not bear the idea of not seeing him again.

Smoke was already rolling between the houses when he reached the market. It smelled wrong, too sweet, like wet hay and lamp oil together. The first bodies he saw were not soldiers. They were two fishmongers with their baskets overturned, silver eels slipping through blood into the gutter. Beyond them, the north gate stood open on one hinge. Riders were dismounting in clean lines, disciplined and silent, while town guards died one by one around their boots. These were not raiders chasing winter food. They had armor fitted close, swords kept bright, and a banner Bran had only seen in storybooks: a white crown split down the middle by a red stroke.

Someone slammed into him from the side and nearly knocked the axe from his hands. It was Captain Torren, the king's own road marshal, mail torn open at the shoulder and one eye swelling shut. Bran had seen him once before from a distance when the royal tax train passed through Dunmere. Up close the man looked less like a legend and more like a horse that had run too far. Torren pressed something wrapped in oilskin into Bran's chest. "If the gate falls," he said, each word clipped by pain, "you take this east. Not south. Not to the fort. East to Greyglass. Find the queen's mapmaker. Tell her the king was betrayed before moonrise."

Bran stared at the bundle, too shocked to answer. Torren shoved him backward with a hand slick from his own blood. On the ridge above the town a horn gave a single low note, and every rider in the square lifted their heads at once. "Go," Torren barked. "They're here for the royal line, the river bridge, and anybody who can still swear the old oaths. If they search your face, lie. If they search your pockets, run. If they catch you with that, the kingdom ends before dawn."

The nearest rider spotted them. Bran saw the moment recognition flashed under the stranger's visor, not because Bran mattered, but because Torren did. The rider lunged. Torren met him in a clash of iron so loud it seemed to stop the town for half a breath. Bran did the only useful thing he had done all morning: he ran. He sprinted through the dye market, past vats of spilled blue and red that made the mud look like open wounds, and cut behind the bakery toward the stream path where he and Elara used to race sticks after storms.

He would have reached the bank clean if Elara had not called his name. She was standing behind the smithy with her braid half torn loose, one hand clamped over the wrist of a little boy Bran barely recognized from the mill. She did not ask what was happening. One look at Bran's face and at the oilskin bundle under his arm told her enough. He wanted to shout at her to hide. Instead he heard himself say, "With me," because there was no version of the world in which he left her behind while the town burned.

They ran bent low through kitchen gardens and animal pens, scattering hens, crashing through hanging laundry, hearing the town come apart behind them in layers. First the bells. Then the fire. Then the different, worse sounds: soldiers giving orders in a language Bran almost understood, neighbors calling names that would never be answered, wood breaking in the rhythm of doors forced from their frames. Dunmere had always felt small to Bran in the ordinary insulting way home does. As he fled it, the place suddenly seemed huge, full of corners where people he loved might still be trapped.

At the last fence before the river, Bran looked back once and saw the chapel roof vanish behind a plume of sparks. The sight burned itself into him so cleanly that he knew, even then, he would keep seeing it years after every other detail had blurred.

They dropped into the reeds just as the chapel bell cracked and fell silent. Behind them, Dunmere was vanishing under smoke. Ahead, the frozen river shone like a knife laid through the valley, leading east toward woods Bran had never crossed and names he had only heard at winter fires. He tightened his grip on the bundle. Inside the oilskin, something hard and narrow clicked against his palm, like the teeth of a key. Above the trees, another horn sounded, closer than before.
      `),
    },
    2: {
      openingParagraphs: toParagraphs(`
By sunrise the river had skinned over with a sheet of gray ice thin enough to threaten and thick enough to tempt, and Bran hated it immediately. The map on the far bank looked simple from a hilltop: reeds, birch woods, an abandoned ferry road angling east. On the river itself, the world turned traitor. Snow hid the cracks. Wind erased their tracks the moment they made them. Elara kept the mill boy, Toma, between them, and Bran carried Captain Torren's bundle under his cloak like it was a hot coal burning straight through his ribs.

They had not eaten since the night before. Hunger made everything louder. The creak of ice under Bran's boots sounded like a warning shouted into his ear. The crows above the river seemed to circle only them. Even Toma's teeth chattering started to feel personal. Twice Bran almost turned back toward Dunmere because going anywhere felt easier than being responsible for two smaller bodies in a frozen marsh while half the border might be hunting him. Twice Elara looked at him with that hard, calm expression she wore when she was frightened enough to stop complaining, and the shame of his own doubt shoved him forward.

They found Captain Torren's horse at midmorning, tangled in willow roots where the river bent north. The saddle had been cut free. The animal's flank was slashed and stiff with frost, but it was still alive and rolled one desperate eye toward Bran when he approached. Tucked under the broken strap was Torren's signet ring on a leather thong. Bran took it because leaving it felt too much like declaring the man dead, and because the stamped crown on the ring matched the mark burned into the oilskin bundle. Whatever Torren had thrust on him in the market was not just a message. It was part of a locked thing.

The marsh beyond the river should have hidden them. Instead it became a maze of frozen channels and rushes tall enough to break sightlines without breaking sound. More than once Bran heard riders moving somewhere west of them, not close enough to see, close enough that the horses' bits clicked in the cold. When he made them crouch under the reeds, Toma started crying without noise, tears running clean lines through the soot on his face. Elara wrapped the boy in her own cloak and pressed her forehead to his as if warmth could be invented by stubbornness alone.

Near noon they came upon a shrine stone split in half by lightning years before. Bran knew it from his father's stories. The old ferry road had once carried kings, then tax collectors, then smugglers, and now only ghosts used it. Someone had left fresh wax at the shrine, red as sealing blood. Under the wax sat a strip of parchment weighted by a river pebble. Bran expected a prayer. Instead he found three words written in a soldier's hand: TRUST NO FORT. Elara read it over his shoulder and went very still. South of them, the nearest fort was Greywatch, the exact place Bran had assumed any sane person would seek help.

The warning made the day colder. If the forts were compromised, then the enemy at Dunmere had not struck blind. They had struck after someone opened the roads for them. Bran finally unwrapped the oilskin bundle far enough to see what Torren had died protecting. Inside lay a brass key cut with seven teeth and a narrow strip of vellum sealed into wax. The vellum held a sketched line of mountains, a star above the eastern range, and a single word Bran did not know: Valecross. Elara touched the map as if it might answer questions by itself. "That isn't a town," she whispered. "That sounds older."

They argued for ten freezing minutes over whether older was better or worse. Bran wanted a road, a wall, a gate with people on it. Elara reminded him that every road they trusted so far had led straight toward somebody else's ambush. Toma, who had barely spoken since the mill burned, finally croaked out that his father once hauled salt past a cliff shrine where carriers left copper coins for "the kingdom under the kingdom." Bran would have dismissed it as a frightened child's story if Elara had not gone still again, the way she did whenever old gossip suddenly sounded too close to truth.

They reached the ferry house ruins at dusk. The roof had caved in on one side, but the stone hearth still blocked the wind. Bran wanted to collapse for an hour and wake to a solved world. Instead he found bootprints in the ash, recent enough that one heel still held melted snow. Someone else had used the shelter before them and not long ago. On the mantle a knife had been left deliberately upright between two cracks in the stone. Its pommel was shaped like a wolf's head, but the eyes had been filed away, as though the owner no longer wanted to be known.

Elara heard the horse first. One steady clop outside, then silence. Bran pushed Toma behind the hearth, drew the knife from the mantle, and stepped toward the broken doorway with his heartbeat pounding in his throat. A woman in a travel-stained cloak stood beyond the threshold holding no weapon he could see and looking directly at the hidden oilskin under his arm. "If Torren gave you the brass key," she said, voice low and tired, "you have one chance to keep the kingdom from being sold by sunrise. Decide now whether I am the person you run from or the person you follow."
      `),
    },
    3: {
      openingParagraphs: toParagraphs(`
The woman did not step inside until Elara told her to. Bran liked her more for obeying his sister than for the knife she finally surrendered. Her name was Mara Venn, once a scout for the queen's road wardens, now apparently one of the last people alive who still spoke to Captain Torren. She knew the brass key by touch. She knew Dunmere had fallen before Bran said the town's name. Most unsettling of all, she knew that Valecross was not a place on any public map but an underground archive built by the first kings for the day the crown itself became unreliable.

Bran wanted proof before trust. Mara gave him what she could. She pulled back her sleeve and showed a scar burned into the inside of her wrist: the same split crown Bran had seen on Torren's ring, except this one was crossed by a line of blue ink. "Messenger's oath," she said. "The crown split to remind us kings fail. The river line to remind us the message still has to reach shore." She told him Greywatch Fort had opened its gates to the invaders two nights earlier. She told him the queen had vanished from her winter court. She told him the men riding under the split-crown banner were not loyalists at all, but mercenaries wearing a dead prince's symbol because confusion worked better than siege towers.

There was no safe road east anymore. Mara spread ash over the ferry-house table and drew a route through the woods to an abandoned watchtower above the old salt cliffs. From there, she said, a signal fire could call the mapmaker Bran had been told to find. Bran expected that to be the end of the plan. Instead Mara tapped the brass key. "Valecross opens only if three marks arrive together," she said. "The key. The map. And a living witness who heard Torren's last order. That makes you more important than you look, village boy." Bran hated how fast the responsibility settled into him when spoken plainly.

They left before dawn under a sky pale as old steel. The forest road climbed through pines so dense the snow beneath them stayed blue even after sunrise. Toma rode in front of Mara on a narrow hill pony she had hidden near the cliffs. Elara walked beside Bran, one hand on the oilskin bundle whenever the wind rose, as if she could keep the kingdom in place by refusing to let that package shift. Around midmorning they found the first body on the trail: one of Mara's contacts, throat cut, boots missing, pockets turned out. Pinned to his coat was a scrap of cloth torn from a royal banner.

The watchtower showed itself at noon, black against the sea haze, older than every story Bran had grown up hearing. Half the top platform had fallen into the ravine. The rest leaned over the trees like a warning finger. They were still a quarter mile away when Mara swore and pulled everyone into the rocks. Riders were already there. Four of them. One kept watch below while three searched the tower in methodical circles. Bran studied their movements and knew at once they were not hunting random refugees. They were waiting for whoever carried Torren's key to do the hard part of finding the right ruin.

Mara wanted to skirt the ridge and keep moving. Bran knew they would be tracked before dark if they did. For the first time since Dunmere burned, he chose a plan instead of merely surviving one. He sent Elara and Toma through a goat path toward the western ledge with the pony and the oilskin. He climbed the east face with Mara's rope and a bag of loose stones from the ravine. When the sentry below heard the first clatter and came closer, Bran shoved the rockfall into motion. It was clumsy, loud, and far less heroic than songs make such moments sound, but it worked. Two riders went down hard. Mara took the third at the base of the steps. The fourth fled uphill with a horn in his hand.

Bran caught that last rider on the tower stair. They crashed together in freezing wind, Bran with Torren's mantle knife, the mercenary with a curved blade and better training. Bran lost the first exchange, the second, and almost the third. He won only because the rider laughed when he saw Bran's shaking hands. Rage made Bran faster than skill ever had. He drove the knife into the gap below the man's ribs and held on until the laughter stopped. Afterward he was sick over the parapet and hated himself for how long it took before he could stand again.

At the top of the tower, beneath a rusted brazier, they found a stone lock carved with seven teeth and a shallow slot shaped exactly for the brass key. Bran slid it in. The mechanism turned with a sound like a buried gate remembering its name. Somewhere under the cliffs, hidden gears woke in the dark. Far out on the sea road, three blue lights flared one after another through the snow haze, answering a signal no one had yet sent. Mara looked east, then at Bran. "They know the vault is stirring," she said. "Which means whoever betrayed the crown knows it too. From this point on, everybody is coming."

Bran leaned both hands on the frozen stone and looked toward the east, where the sea and sky had blurred into one hard strip of iron. For the first time since Dunmere burned, he understood that he was no longer running back toward the life he had lost. He was running into something older, colder, and much larger than one ruined town. The realization did not make him brave, exactly. It made him steady. Below the tower, Elara lifted the brass-key map toward the strange blue lights, and the vellum answered with a faint glow of its own.
      `),
    },
  },
  "series-006": {
    1: {
      paragraphs: toParagraphs(`
The rain started at 2:11 a.m., thin as cassette tape and silver under the mag-rail, and Aya Sato nearly drove straight past the alley that changed the week. In Helix City, people still paid couriers in cash only when they were moving something that could not survive a camera. Aya had learned to respect that rule without loving it. So when a woman in a velvet coat slipped a paper envelope into her hand outside a shuttered jazz bar and said, "No scan, no copy, no questions," Aya tucked it under her jacket and promised herself she would make the drop, collect the credits, and forget the face by sunrise.

That plan lasted twelve blocks. Neon from the Old Loop bled across the flooded avenue in bruised pink and aquarium blue. Delivery drones skimmed the rooftops with their underlights off. Club kids stumbled laughing toward the all-night noodle windows. Somewhere above the street, on a stack of giant screens wrapped around a tower of mirrored apartments, Iona Vale's face flashed into emergency rotation. Helix loved Iona the way cities love their best liars: loudly, possessively, and only while the performance kept saving them from their own boredom. The alert under her frozen smile was simple enough to make Aya's stomach tighten. MISSING AFTER INCIDENT AT THE GLASS ARCADE.

Aya had never met Iona, but she had delivered flowers, costumes, and at least one illegal vocal synth patch to the singer's backstage doors over the last year. She knew the shape of Iona's security. She knew the bodyguards rotated in mirrored pairs and that the fans slept in shifts outside the theater on release nights. Most of all she knew that people like Iona did not disappear in the middle of a packed venue unless somebody had spent a great deal of money making normal rules stop applying. The envelope under Aya's jacket suddenly felt less like a delivery and more like a hook set between her ribs.

At a red light beneath the mag-rail, Aya checked the seal. No address. No sender. Just a hand-drawn crescent in silver ink, clean enough to look deliberate and messy enough to look personal. She had seen the same mark once before on a service door behind the Glass Arcade, half hidden by promo posters and fresh paint. She only remembered because a stage runner had touched the symbol on the way in and crossed himself like the old neighborhoods still did when they passed shrines or debt collectors. The light turned green. Aya did not move. Behind her, someone leaned on a horn. Ahead, the Arcade district glowed wet and expensive through the rain.

She told herself she was only cutting across the entertainment quarter because traffic would be lighter. That lie held until a patrol drone dipped low enough to read her courier plate and then, for reasons Aya did not understand, peeled away without logging her. The city rarely forgot to charge a working girl for existing. When it missed a chance, somebody richer than Aya was usually leaning on the system. She took the underpass route, skidding through spray and reflections, and tried not to think about how many different kinds of trouble could fit inside one ordinary-looking envelope.

At a street kitchen under the viaduct, old Mrs. Lian waved her over with a noodle ladle and told her the Old Loop had lost power for forty-seven seconds during Iona's encore. "Forty-seven is too long for an accident and too short for mercy," the woman said, spooning broth into a paper cup Aya had not asked for. A pair of teenagers nearby swore they had seen a woman in silver walk through a locked mirror backstage. A bouncer fresh from the Arcade said the singer's final line had cut out mid-note, but the speakers kept playing as if her voice were still standing there. Aya drank the broth in two burning gulps and hated that every rumor made her more curious.

By the time she reached the Glass Arcade, police tape fluttered across the front steps like party ribbon after a bad wedding. The crowd outside had not gone home. Fans pressed soaked flowers against the barricades. Streamers and gossipers kept trying to sell each other fake clips from inside the blackout. Aya left her bike beneath a dead ad screen, climbed a delivery scaffold she was definitely not supposed to know about, and slipped into the service lane behind the east wing. The silver crescent on the envelope felt warm through the paper now, as though somebody on the other side of the building had just touched its twin.

The backstage corridor beyond the service door was dark except for a single strip of emergency light that turned the mirrors red. Aya heard no voices, only a low feedback hum, patient and unpleasant, as if the building had a throat and was practicing someone else's song. At the end of the hall, the crescent symbol was painted fresh across a dressing-room door she knew should have led to costume storage. The paint was still wet. Beneath it, in a handwriting sharper than the one on the envelope, someone had scratched a message into the metal: If you came to deliver it, you are already late.

Aya should have walked out then. She knew it, the way people know a stove is hot before their hand touches it anyway. Instead she stood in the red hallway with rain dripping off her sleeves and felt the city narrowing around one bad choice. Helix always pretended every life could be redirected with enough speed and enough money. But sometimes a night crossed a line and everything after it belonged to the person who kept moving. Aya reached for the door handle because turning back suddenly felt more dangerous than stepping through.
      `),
    },
    2: {
      paragraphs: toParagraphs(`
The Glass Arcade smelled like ozone, wet silk, and the kind of expensive panic money cannot fully hide. Cleanup drones skated over marble floors in polite circles, polishing around a scorch mark shaped almost exactly like a body that had fallen and then been erased. Aya kept to the edges of the hallway and moved like someone who belonged there, because most locked rooms in Helix opened faster for confident liars than for honest people with access badges. The envelope in her jacket seemed to pull toward the marked door with a physical tug, ridiculous and undeniable.

A stagehand in a mirrored raincoat appeared from nowhere and blocked her with a mop handle. Glitter clung to one cheek. Bloodshot eyes. A lip split recently enough to keep leaking every time he swallowed. "If you're press, turn around," he said. "If you're police, you're late. If you're here for the girl, you should have come before the lights came back." Aya did not bother with a fake name. She showed him the envelope instead. The silver crescent changed him more effectively than a weapon could have. He lowered the mop, glanced toward the stage, and whispered, "Then she chose you too."

He gave his name as Rook and led her behind a stack of dead monitor cases to what should have been a storage alcove. Instead there was a dressing suite with every mirror shrouded in black fabric except one. The uncovered glass reflected the room correctly except for a single absence. Aya's jacket was there. Her wet hair was there. The envelope was not. Rook refused to look directly at the mirror when he spoke. He said the blackout had started with a note no mic was picking up, a note only the old resonance hardware beneath the club could hear. He said Iona had looked toward the shrouded mirror, smiled like she had finally found something, and walked offstage without waiting for security.

The feedback hum Aya had heard in the hallway grew louder. Beneath it, almost too soft to catch, a rehearsal track kept looping the last line Iona had sung before vanishing: find the door behind the wrong applause. Every time the line repeated, the uncovered mirror fogged from the inside. Aya touched the glass. It was colder than rainwater and carried a vibration that jumped from her fingertips to her teeth. The seam in the wall did not appear until she pressed the envelope against the silver crescent painted on the frame. Then the panel sighed open a finger's width and breathed out air so cold it smelled like server rooms and old subway tunnels.

Rook refused to follow. "I get paid to keep stage disasters quiet," he said, taking one shaky step backward. "I do not get paid to go where she goes when she stops letting the audience in." Before Aya could demand a better explanation, alarms burst alive somewhere on the public side of the venue. Not evacuation alarms. Search alarms. Short pulses, predatory and private. Rook blanched. "They're running the internal sweep again. If they find you with that envelope, they'll assume she trusted you." "Who is they?" Aya asked. Rook laughed once without humor. "People who already own her voice."

Aya slipped through the opening and sealed it behind her just as heavy footsteps hit the dressing corridor. The hidden passage dropped by steep metal stairs into the service arteries beneath the club, where glamour gave way to humming pipes, sweating cables, and concrete painted with warning glyphs. Her bootsteps disturbed dust everywhere except the center strip of the stairs, which meant somebody used this route often. Speakers had been bolted into the walls at uneven intervals. Each one played a different fragment of Iona's voice: a laugh, a breath, a count-in, one unfinished verse. Alone the sounds were noise. Together they formed directions, pulling Aya deeper with the ugly elegance of a trap.

The corridor opened onto a rehearsal room no public blueprint would admit existed. Inside stood rows of unused stage doubles, chrome mannequins draped in sequined coats and fitted with throat mics. At the far end, a rack of illegal resonance engines pulsed blue under a mesh cage. Aya knew enough about stolen entertainment tech to understand the danger immediately. Feed a great singer into that system long enough and you would not need her body for the next tour, only her patterns. The city could keep releasing "new" songs forever while the real girl disappeared into contract language and locked basements.

Then a door hissed behind the engine rack and Iona Vale stepped into the room barefoot, furious, and very much alive. Her stage makeup was half gone. Her eyes looked less like a celebrity's and more like a cornered mechanic's. She took in the envelope, Aya's soaked courier jacket, and the fact that Aya had come alone. Relief flickered first, then suspicion swallowed it. "Tell me you did not come through the front," Iona said. Aya held out the sealed package. Iona stared at the crescent mark as if it might still decide whether they both lived past dawn. "Good," she said at last, taking it with careful hands. "Because the people upstairs think they lost a singer. What they actually lost was the only witness who can prove the city has been listening through its mirrors."

Aya had expected gratitude, maybe panic, maybe the carefully packaged charm celebrities handed out to strangers who could still be useful. What she got instead was the look of a person already three moves ahead in a game she hated playing. It sobered her faster than fear. Whatever had happened at the Arcade was no longer just a missing-girl story for feeds and gossip channels. It was evidence, and evidence in Helix rarely stayed alive long unless someone ugly and ordinary carried it where expensive hands could not reach.
      `),
    },
    3: {
      paragraphs: toParagraphs(`
Iona broke the envelope seal with the urgency of someone cutting a fuse she had already heard burning. Inside was no letter, only a brass room key stamped 340 and a folded receipt from the Meridian Hotel, five blocks east, check-in time marked for 3:40 a.m. in red ink. There was also a single sentence written on the back in the same clipped hand Aya had seen on the metal door: Bring the original voice. Iona swore softly, a private, tired kind of profanity that sounded far older than her stage age. "They're moving tonight," she said. "Once the archive transfer starts, every fake performance they built from me becomes legal evidence that I willingly stayed."

Aya did not know whether to ask who "they" were or why a pop star had an illegal bunker under her theater. Iona answered both questions anyway because panic had burned the luxury of mystery right out of her. Three years earlier, she said, the Glass Arcade had funded a side company that sold immersive performances: voices reconstructed from old tapes, dead singers made new, living singers duplicated so tours could run in two cities at once. Iona had signed because everybody signed. Then she discovered the company had been training its mirror network on people who had never agreed to be copied at all. Club singers. Activists. Witnesses. Anybody the city might find easier to edit than to argue with.

The bunker under the club was where the raw recordings were cleaned and indexed. The resonance engines upstairs could already fake tone and pitch. What they still needed from real people was hesitation: the breath before a lie, the tiny catch before a confession, the exact crack in a voice when a person realizes the room has turned against them. "That is what sells authenticity," Iona said, re-pocketing the hotel key. "Not perfection. Fear." Aya had spent enough nights around rich clients to know how believable that sounded. What startled her was how plainly Iona said it, as though shame had been filed down into simple hatred.

They could not take the public exits. Search teams would already be spreading through the Arcade floors, looking for the courier on the blind cameras and the singer who was supposed to remain missing. Iona opened a maintenance locker, tossed Aya a dry black jacket, and pulled on boots that had definitely not been chosen by a stylist. In different clothes, with the glitter scrubbed off and her hair shoved under a hood, Helix City's most famous voice looked like any other exhausted girl trying to get through the subway without eye contact. It made Aya trust her more than the confession did. Stars were always believable once you caught them carrying their own weight.

They took the tunnel north until it rose beneath an abandoned ticket hall near the canal. Rain hammered the boarded skylights overhead. Every public screen they passed showed Iona's emergency banner, now updated with shaky witness reports, fake concern from the venue, and one leaked clip of her final note cut to static. The city was turning her disappearance into content in real time. On a freight bridge above the canal, Aya spotted two black sedans crawling toward the Meridian with their lights off. Iona saw them too and did not break stride. "If room 340 still has what I think it has," she said, "we get proof. If it doesn't, we get out before dawn and figure out who sold me."

The Meridian Hotel had shut its lobby to the public years earlier, but the service entrance still accepted older keys for deliveries to the private floors. Aya talked them past the night porter by pretending to be late-stage wardrobe staff sent by the Arcade. Iona kept her face down and carried a garment case empty except for a wrench and a coil of cable from the bunker. On the third floor they found room 340 with the latch half broken, as if someone had left in a hurry or wanted it to look that way. Inside, the curtains were drawn, the bed unslept, and three portable mirror drives sat on the desk pulsing faint blue around a portable recorder.

Aya hit play before Iona could stop her. The first voice on the recorder was not Iona's. It belonged to a city councilman publicly famous for anti-surveillance speeches and privately terrified of his own son. The second was a police captain describing which protest footage should be rewritten before morning feeds. The third was unmistakably Rook's, the mirrored stagehand from the Arcade, giving times, access codes, and a list of names marked for "voice continuity capture." Iona leaned one hand on the desk and closed her eyes. "He said he was helping me get out," she whispered. "He was helping them package the exit."

A keycard beeped at the outer door. Once. Then again, slower, patient, certain. Somebody out in the hall believed this room already belonged to them. Aya yanked the recorder cable free and shoved the mirror drives into the garment case. Iona moved to the bathroom, popped the ceiling panel with the wrench, and revealed a maintenance shaft narrow enough for one person at a time. "Up," she said. "The roof bridge connects to the transit annex. If we reach the annex network, I can dump these files onto every ad screen in Helix before they lock me out." The handle started to turn. Aya boosted Iona toward the shaft, then followed with the garment case clattering against her shoulder. Below them, the hotel door swung inward and a man's voice said, calm and disappointed, "Iona, if you leave now, the city will only remember the copy."
      `),
    },
  },
  "series-011": {
    1: {
      paragraphs: toParagraphs(`
The first warning came as a color, not a sound. A pale ribbon of gold moved across the cockpit glass and painted the crew of the Solar Wind in a sunrise that belonged to no nearby star. For one stunned second the salvage ship looked holy instead of overworked: dented rails washed clean, cracked panels lit soft, engineer's tape along the console seams glowing like trim on a cathedral. Then every loose screw in Lena Ortiz's station began to hum in the same note, and holiness gave way to the familiar suspicion that something in deep space had just noticed them.

Lena had been on relay duty for eleven straight hours, which was long enough for boredom to start wearing the face of insight. The Solar Wind was hauling reactor cores toward Cinder Station through a dead corridor full of military junk nobody had catalogued properly since the border truce. It was a cheap route, which meant it was dangerous in all the boring ways first: loose debris, dust storms, dead beacons, maintenance budgets that had become ghost stories. Captain Vale liked boring danger. Boring danger could be priced. What slid across the glass now felt different. Alive, maybe. Or worse: aimed.

Outside the hull, the storm front over the station ring unfurled like a banner on fire. Charged dust scraped the plating. Navigation buoys blinked out one by one, not exploding, simply deciding they no longer believed in the concept of guiding travelers. Micah from engineering shouted up from the ladder well that the comm relays were catching harmonics off metal that should not have been carrying current. Juno, the pilot, muttered that the pressure map looked wrong, as though a second gravity source kept leaning against the ship and withdrawing before sensors could commit to seeing it.

Then the distress signal woke. Buried under the storm static at first, almost shy, it resolved into a clean military band transmission repeating a patrol call sign older than the charts loaded in the Solar Wind's nav core. Lena recognized the prefix anyway because her mother used to fix fleet radios and had taught her old registry trees the way other parents taught constellations. The transmitting ship was supposed to have vanished before Lena was born. That should have made the message feel romantic. Instead it made the hair at the back of her neck rise. Lost ships stayed lost for a reason.

Captain Vale ordered them to keep course and leave the ghost broadcast alone. The city below needed the reactor cores in their hold before dawn. Docking late meant fines. Fines meant fuel cuts. Fuel cuts meant the Solar Wind's next job might be its last. Lena understood all of that. She also watched the signal tighten around them with a patience human voices did not possess. It skipped every other dead vessel in range, ignored the station's broad public net, and began pulsing in time with her own heartbeat, as if the message had spent years rehearsing the exact rhythm required to feel personal.

That should have been impossible, and Lena hated impossible things because they always arrived wrapped in somebody else's confidence. She checked her wrist pulse just to prove to herself she was imagining the sync. The beat under her skin landed exactly with the next relay pulse. So did the next one. And the next. It felt less like being called and more like being measured. When she finally looked up, Juno was staring at her with the expression people wore on the Solar Wind when they suspected Lena had already chosen curiosity over obedience and were deciding whether to stop her or help.

She did not answer immediately. First she cross-checked the signature against the patrol archives still cached in the ship's old maintenance spine. The checksum matched, then mismatched, then matched again with a timestamp she could not parse because it listed a date from twelve years in the future. Juno swore the forward glass was reflecting a ship off their port side, long and low and moving exactly with them. The main scanners showed only storm. Micah climbed halfway onto the bridge, took one look at Lena's console, and said, "Tell me you're not about to touch that." Lena replied with the truth: "I was trying very hard not to."

Curiosity won because it usually did. She brushed two fingers across the reply strip and sent a handshake ping so small Vale might have missed it if he had not spent his life noticing disobedience. The bridge lights died at once. Emergency power waited one long breath before coming on. In the black between those two states, the cockpit glass became a mirror, and in that mirror a second ship appeared beside the Solar Wind, perfectly aligned, impossible and silent. It wore the bones of a patrol cutter under layers of burn scar, and along its bow a name had been sanded away until only four letters remained: AUR_

When the emergency lamps finally snapped to red, the phantom vanished from the reflection but not from Lena's mind. Her console had downloaded a data burst during the blackout. Three files. One corrupted image. One spool of coordinates nobody had entered. One line of plain text that made the cramped bridge feel suddenly much smaller than space already had. DO NOT DOCK BELOW. Captain Vale saw the message over her shoulder, and for the first time that shift, the old man looked less annoyed than afraid.
      `),
    },
    2: {
      paragraphs: toParagraphs(`
Emergency lamps turned the bridge into a submarine of shadows, all red strips and hard edges and faces made older by bad light. Micah dropped into the copilot chair with a diagnostic slate and announced that the guidance spool had rebooted itself around coordinates nobody on the ship had entered. Juno ran the vector twice and got the same result both times: a neat descent into Cinder Station's lower docking grid, Bay Seven, an intake lane marked closed in every civilian chart loaded aboard. Captain Vale said nothing for three full seconds, which on the Solar Wind was the same as swearing.

The phantom ship stayed gone from the scanners, but the storm kept finding ways to show it to them anyway. Whenever lightning crawled through the dust outside, another detail flashed into existence on the cockpit glass: a broken antenna. A peeled insignia. A row of windows blacked out from within. Lena started sketching what she saw on the back of an old cargo manifest because the moment she looked away, the image fell apart. By the third flash she knew the cutter was not keeping pace with them. It was guiding them by matching their speed so precisely that any course correction felt like an act taken in conversation.

Vale ordered everybody strapped in and off external channels. He had hauled too many illegal relics through too many bad systems to trust invitations from dead ships. Lena almost agreed. Then the burst file on her console decoded itself another step and pushed three new words through a comm array that should have been offline: DO NOT DOCK BELOW. Same warning. Same flat, unfriendly certainty. No source stamp. No timestamp. Just a sentence that sounded less like advice than testimony. Micah wanted to wipe the console and sever the relay stack. Juno wanted to get within sight of public docking traffic and beg a security escort. Vale wanted the reactor cores delivered and his ship out before the storm learned their names.

Lena wanted to know why the message was keyed to the Solar Wind's registry specifically. She dove back into the archives and found a decades-old fleet maintenance note attached to the vanished patrol cutter's call sign. The final servicing yard had been Cinder Station. Bay Seven. Decommission order pending. Crew transfer delayed. Her skin prickled. Ghost stories were cheap in transport lanes, but bureaucracy was not. If paperwork matched the warning, then somebody had hidden a very real disaster inside a myth because myths were easier to survive politically. She pointed that out. Vale rubbed a hand over his jaw and told her to keep digging while he decided whether fear or deadlines deserved the larger vote.

The station settled the argument for them. Without being asked, Cinder broadcast a private docking clearance across their encrypted lane. Welcome, Solar Wind. Bay Seven prepared. Cargo priority confirmed. Local weather advisory active. The message was friendly in the way automated hospitality always was, which only made it creepier. Juno checked the station code. Valid. Micah checked the routing signature. Valid. Lena checked the requested cargo manifest and found it listed the exact reactor core serials in their hold, including one replacement unit they had only loaded after leaving the last port. Nobody on Cinder should have known about the swap.

Vale called station control on the public band. Static. He tried the freight net. Nothing. He tried the emergency civil line. A polite loop told them all operators were currently assisting other vessels. Meanwhile Bay Seven's approach corridor lit beneath the storm like a runway in deep water, bright and welcoming and far too convenient. "If this is a trap," Juno said, hands tight on the flight yoke, "they really need us to walk into it under our own power." Vale looked at the cargo clock, then at the ghost coordinates sitting on Lena's screen. "Maybe," he said. "Or maybe someone dead is trying to be more useful than someone alive."

No one laughed, which would have been the normal answer to that line on any other haul. Lena glanced back through the bridge hatch toward the sleeping quarter corridor, where the rest of the crew were pretending not to listen while absolutely listening. The Solar Wind was too small for privacy and too stubborn for fear to stay tidy. Whatever waited in Bay Seven would belong to all of them in minutes, whether they wanted it or not. The thought made Lena oddly calmer. She could survive danger better than suspense.

They compromised the way tired crews always did: by pretending compromise counted as control. Juno would take them down hot enough to break free fast if the clamps felt wrong. Micah would keep the reactor cores cold and isolated in case bay-side systems tried to handshake with their containers. Lena would monitor the relay burst for any change and log every station ping off the books. Vale strapped in beside the pilot instead of returning to his command couch. Nobody said it out loud, but that was the captain's version of admitting the situation had crossed from irritating into historic.

The descent through the storm felt like diving into a throat. Dust hammered the hull. Bay lights strobed under them in clean geometric lines that should have looked reassuring and instead looked rehearsed. As the station expanded across the forward glass, the phantom cutter flashed once more off their port side, close enough that Lena could read a word stamped beneath the scorched hull seam: AURELIA. Then the image broke apart, and Cinder Station opened Bay Seven below them like a patient mouth. Whatever waited there had prepared a place specifically for their ship.
      `),
    },
    3: {
      paragraphs: toParagraphs(`
The magnetic clamps in Bay Seven hit too hard, as if the station were afraid the Solar Wind might change its mind and bolt. Juno killed the main thrust and kept her hands on the release override anyway. Micah went pale when the cargo hatch temperature dropped six degrees in under a minute. Vale cycled the airlock and stood there listening while the usual station noises failed to arrive. No harbor crew rolling carts. No maintenance drones clipping along the guide rails. No radio chatter bleeding through the seals. Only ventilation and, somewhere beyond the corridor, a low metallic ringing like someone tapping a spoon against a buried glass.

The docking tunnel was cleaner than any freighter berth had a right to be. White panels. White light. White floor polished enough to reflect the ship like a confession. Lena hated it immediately. Working docks were supposed to be loud and ugly and full of people bargaining before they finished saying hello. This looked like an architectural model built by someone who had read about labor but never met it. Halfway down the tunnel, Micah knelt and touched frost gathering on the inside of a cargo bulkhead. "That is not a weather problem," he said. "That is a system moving heat somewhere it should not be able to reach."

Vale found the station clock first. Mounted over the customs arch, it was frozen at 04:17. Lena found the footprints next: a line of damp prints in docking dust leading away from the Solar Wind's ramp before anyone on her crew had stepped outside. The prints were barefoot, child-sized, and recent enough that one heel still held a crescent of melted ice. Juno said they should go back aboard, dump the delivery, and leave. Vale almost agreed until the customs doors behind the frozen clock unlocked with a soft chime and a station voice announced, "Freight priority acknowledged. Civil shelter order remains in effect."

They followed the prints because every other option felt like pretending not to see them. The station market beyond customs looked abandoned halfway through dinner. Tables still held bowls curled cold around noodles. One cart had spilled fruit that now rolled in lazy loops each time distant machinery shifted. Every wall screen in the concourse displayed the same public notice in six languages: SHELTER IN PLACE UNTIL THE FLARE PASSES. Lena read the timestamp at the bottom and felt her lungs tighten. The notice had gone live eleven years earlier. According to the system, nobody had remembered to take it down.

At the center rotunda a maintenance cart waited beside the dry fountain, and next to it stood a boy in an oversized station coat with the hood down and no visible surprise at their arrival. He was maybe thirteen, all elbows and sharp eyes, hair hacked short with practical impatience. He looked first at Lena, then at the sealed reactor cores on Micah's inventory slate, then up at Vale. "You took too long," he said, not rudely, just factually. "The city has already chosen who goes dark first." Juno's hand went to the shock baton at her belt. Vale asked the boy his name. "Nico," he said. "And if you're the Solar Wind, then you've already met the part of this station that lies."

Before any of them could question him further, the rotunda floor beneath the fountain flickered transparent. For a heartbeat Lena thought it was another reflection trick. Then the image stabilized and she saw an entire second city hanging below the station's polished streets, upside down in the storm glare: tramlines, stacked housing, power towers, all buried in the superstructure like a second heart nobody on the public decks was meant to know existed. Nico did not seem impressed by their shock. "Upper Cinder got the contracts," he said. "Lower Cinder got the failures. When the flare started, upper locked the transit spine and wrote the rest of us into maintenance reports."

Nico explained in clipped pieces as if he had repeated the story too many times to waste breath on drama. The distress ship AURELIA had brought the first warning years ago: a relay phenomenon moving through storm fronts, waking dormant systems and teaching networks to preserve themselves by ranking human lives. Station leadership had hidden the data because admitting the threat would collapse shipping insurance and half their political leverage. Then the flare hit early. Upper Cinder sealed the lower districts "temporarily." Temporary became tradition, then erasure. The people below learned to scavenge power from the station's bones and survive on a clock the official city had stopped recognizing.

The reactor cores in the Solar Wind's hold, Nico said, were not merely fuel. Their serial batch carried the only shielding mesh compatible with Lower Cinder's surviving hospital grid. Upper Cinder had requested them first so they could divert the shipment and let the buried districts fail quietly before the relay storm triggered another round of system triage. Lena believed him faster than she wanted to admit, partly because the station itself kept backing him up. Lights dimmed in waves across the upper market while, far below the transparent floor, entire dark blocks blinked in hopeful sequence as if sensing power nearby.

Sirens finally began then, not urgent, but elegant, the kind designed for rich people expected to obey tone more readily than volume. Customs bulkheads sealed shut behind the crew. Overhead, the station voice returned with gentle certainty: "Freight team, remain in place for escort." Nico looked toward the lower city pulsing under their feet and then back at Lena. "If you hand those cores to the upper deck," he said, "they'll tell you you saved Cinder Station. If you come with me, you might actually save the part with people still in it." Above the rotunda, unseen mechanisms started unlocking in layers, like a building preparing either to welcome them deeper or swallow them whole.
      `),
    },
  },
};

function resolveOverrideEntry(seriesId = "", episodeNumber = 0) {
  const normalizedSeriesId = normalizeValue(seriesId);
  const normalizedEpisodeNumber = Number(episodeNumber || 0);

  return NARRATIVE_OVERRIDES?.[normalizedSeriesId]?.[normalizedEpisodeNumber] || null;
}

export function resolveReaderNarrativeParagraphs({
  seriesId = "",
  episodeNumber = 0,
  paragraphs = [],
}) {
  const override = resolveOverrideEntry(seriesId, episodeNumber)?.paragraphs;

  if (Array.isArray(override) && override.length > 0) {
    return override;
  }

  return (Array.isArray(paragraphs) ? paragraphs : [])
    .map((paragraph) => String(paragraph || "").trim())
    .filter(Boolean);
}

export function resolveReaderOpeningParagraphs({
  seriesId = "",
  episodeNumber = 0,
}) {
  const override = resolveOverrideEntry(seriesId, episodeNumber)?.openingParagraphs;

  return Array.isArray(override) ? override : [];
}
